#!/usr/bin/env bash
set -xeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export EXP_NAME=${EXP_NAME:-qwen3_omni_megatron_lora_4gpu_gspo_aligned}
export STAGE_CONFIG=${STAGE_CONFIG:-${SCRIPT_DIR}/qwen3_omni_thinker_only_tp4_gspo_aligned.yaml}
export TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-200}

export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-8}
export MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-1024}
export MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-8192}
export MAX_POSITION_EMBEDDINGS=${MAX_POSITION_EMBEDDINGS:-9216}

export LORA_RANK=${LORA_RANK:-64}
export LORA_ALPHA=${LORA_ALPHA:-32}

export ACTOR_LR=${ACTOR_LR:-1e-6}
export ACTOR_LR_WARMUP_STEPS=${ACTOR_LR_WARMUP_STEPS:-10}
export ACTOR_WEIGHT_DECAY=${ACTOR_WEIGHT_DECAY:-0.1}
export ACTOR_CLIP_GRAD=${ACTOR_CLIP_GRAD:-1.0}
export PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-8}
export PPO_MICRO_BATCH_SIZE_PER_GPU=${PPO_MICRO_BATCH_SIZE_PER_GPU:-1}
export POLICY_LOSS_MODE=${POLICY_LOSS_MODE:-gspo}
export LOSS_AGG_MODE=${LOSS_AGG_MODE:-seq-mean-token-mean}
export CLIP_RATIO_LOW=${CLIP_RATIO_LOW:-3e-4}
export CLIP_RATIO_HIGH=${CLIP_RATIO_HIGH:-4e-4}
export USE_KL_LOSS=${USE_KL_LOSS:-False}
export KL_LOSS_COEF=${KL_LOSS_COEF:-0.0}

export ROLLOUT_N=${ROLLOUT_N:-8}
export ROLLOUT_TEMPERATURE=${ROLLOUT_TEMPERATURE:-0.8}
export ROLLOUT_TOP_P=${ROLLOUT_TOP_P:-0.9}
export ROLLOUT_TOP_K=${ROLLOUT_TOP_K:--1}
export ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.40}
export ROLLOUT_CALCULATE_LOG_PROBS=${ROLLOUT_CALCULATE_LOG_PROBS:-True}
export ROLLOUT_MAX_MODEL_LEN=${ROLLOUT_MAX_MODEL_LEN:-9216}
export ROLLOUT_MAX_NUM_SEQS=${ROLLOUT_MAX_NUM_SEQS:-32}
export ROLLOUT_MAX_NUM_BATCHED_TOKENS=${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-32768}

export REWARD_MANAGER=${REWARD_MANAGER:-dapo}
export ENABLE_OVERLONG_BUFFER=${ENABLE_OVERLONG_BUFFER:-True}
export OVERLONG_BUFFER_LEN=${OVERLONG_BUFFER_LEN:-4096}
export OVERLONG_PENALTY_FACTOR=${OVERLONG_PENALTY_FACTOR:-1.0}
export OVERLONG_BUFFER_LOG=${OVERLONG_BUFFER_LOG:-False}

exec "${SCRIPT_DIR}/run_qwen3_omni_megatron_lora_4gpu_smoke.sh" "$@"
