#!/usr/bin/env bash
# 8-GPU single-node Qwen2.5-Omni-3B fully-async GSM8K RL long run.
#
# Defaults to 300 fully-async parameter-sync steps on one 8-GPU pod:
#   4 GPUs Megatron actor/ref + 4 GPUs standalone vLLM-Omni rollout.
# It reuses the validated 8-GPU smoke launcher for k8s/Ray port handling.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export PROJECT_NAME=${PROJECT_NAME:-qwen25_omni_megatron_async_e2e}

RUN_ID_SOURCE=${RUN_ID:-${LUBAN_JOB_ID:-${AIP_JOB_ID:-${VC_JOB_ID:-${JOB_ID:-${APP_ID:-${K8S_APP_ID:-qwen25_8gpu_e2e300_$(date +%Y%m%d_%H%M%S)}}}}}}}
RUN_ID_SAFE="$(printf '%s' "${RUN_ID_SOURCE}" | tr -c 'A-Za-z0-9_.-' '_')"
export RUN_ID=${RUN_ID_SAFE}
export EXP_NAME=${EXP_NAME:-qwen25_omni_megatron_8gpu_fully_async_e2e300_${RUN_ID}}
export PROFILE_LABEL=${PROFILE_LABEL:-8-GPU Qwen2.5-Omni GSM8K fully-async aligned 300-step run}

export TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-300}
export REQUIRE_BATCHES=${REQUIRE_BATCHES:-1}
export ASYNC_TRIGGER_PARAMETER_SYNC_STEP=${ASYNC_TRIGGER_PARAMETER_SYNC_STEP:-4}
export ASYNC_STALENESS_THRESHOLD=${ASYNC_STALENESS_THRESHOLD:-0.1}
export ASYNC_PARTIAL_ROLLOUT=${ASYNC_PARTIAL_ROLLOUT:-True}
export PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-16}
export PPO_MICRO_BATCH_SIZE_PER_GPU=${PPO_MICRO_BATCH_SIZE_PER_GPU:-1}
export LOG_PROB_MICRO_BATCH_SIZE_PER_GPU=${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-1}
export N_RESP_PER_PROMPT=${N_RESP_PER_PROMPT:-5}
export TOTAL_ROLLOUT_STEPS=${TOTAL_ROLLOUT_STEPS:-$((PPO_MINI_BATCH_SIZE * REQUIRE_BATCHES * ASYNC_TRIGGER_PARAMETER_SYNC_STEP * TOTAL_TRAINING_STEPS))}

export SAVE_FREQ=${SAVE_FREQ:-50}
export TEST_FREQ=${TEST_FREQ:-25}
export VAL_MAX_SAMPLES=${VAL_MAX_SAMPLES:-128}

export MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-256}
export MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-768}
export MAX_MODEL_LEN=${MAX_MODEL_LEN:-1024}
export ROLLOUT_TEMPERATURE=${ROLLOUT_TEMPERATURE:-1.0}
export ROLLOUT_TOP_P=${ROLLOUT_TOP_P:-1.0}
export ROLLOUT_TOP_K=${ROLLOUT_TOP_K:--1}
export LR_WARMUP_STEPS=${LR_WARMUP_STEPS:-10}

export ACTOR_LR=${ACTOR_LR:-1e-6}
export ACTOR_USE_KL_LOSS=${ACTOR_USE_KL_LOSS:-True}
export ACTOR_KL_LOSS_COEF=${ACTOR_KL_LOSS_COEF:-0.001}
export ACTOR_ENTROPY_COEFF=${ACTOR_ENTROPY_COEFF:-0}
export ACTOR_CLIP_RATIO_LOW=${ACTOR_CLIP_RATIO_LOW:-0.2}
export ACTOR_CLIP_RATIO_HIGH=${ACTOR_CLIP_RATIO_HIGH:-0.2}
export ACTOR_CLIP_RATIO_C=${ACTOR_CLIP_RATIO_C:-3.0}
export ACTOR_LOSS_AGG_MODE=${ACTOR_LOSS_AGG_MODE:-token-mean}
export ACTOR_OPTIM_CLIP_GRAD=${ACTOR_OPTIM_CLIP_GRAD:-1.0}

export ROLLOUT_AGENT_NUM_WORKERS=${ROLLOUT_AGENT_NUM_WORKERS:-1}
export ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.40}
export ROLLOUT_MAX_NUM_SEQS=${ROLLOUT_MAX_NUM_SEQS:-16}
export ROLLOUT_MAX_NUM_BATCHED_TOKENS=${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-4096}

export VERL_OMNI_PHASE_GENERATION_DEBUG=${VERL_OMNI_PHASE_GENERATION_DEBUG:-0}
export VERL_OMNI_WEIGHT_SYNC_DEBUG=${VERL_OMNI_WEIGHT_SYNC_DEBUG:-0}
export VERL_OMNI_LOGPROB_DEBUG_LIMIT=${VERL_OMNI_LOGPROB_DEBUG_LIMIT:-0}
export VERL_OMNI_GENERATION_DEBUG_LIMIT=${VERL_OMNI_GENERATION_DEBUG_LIMIT:-0}
export NCCL_DEBUG=${NCCL_DEBUG:-WARN}

exec "${SCRIPT_DIR}/run_gspo_qwen25_omni_megatron_8gpu_fully_async_smoke.sh" "$@"
